/**
 * src/hooks/useProactiveInsights.ts
 *
 * Computes proactive alert banners from the Zustand store.
 * These are shown at the top of the AI Agent chat — generated by
 * application logic, never by Groq.
 */

import { useMemo } from 'react';
import { usePortfolioStore } from '../store/portfolioStore';
import { formatINR, formatNumber } from '../utils/format';
import { calculateNetWorth, investedValue, currentValue } from '../utils/calculations';

export type InsightSeverity = 'danger' | 'warning' | 'good' | 'info';

export interface ProactiveInsight {
  id: string;
  emoji: string;
  title: string;
  body: string;
  severity: InsightSeverity;
  /** Pre-fills the chat input when tapped */
  question: string;
  /** Route to the relevant page */
  linkTo?: string;
}

function todayISO() { return new Date().toISOString().slice(0, 10); }
function inDaysISO(d: number) { return new Date(Date.now() + d * 86400000).toISOString().slice(0, 10); }

export function useProactiveInsights(): ProactiveInsight[] {
  const {
    investments,
    liabilities,
    cashflows,
    trackedPayments,
    insurancePolicies,
    goals,
    goalContributions,
    lendingBorrowers,
    lendingTransactions,
    essentials,
  } = usePortfolioStore.getState();

  return useMemo(() => {
    const insights: ProactiveInsight[] = [];
    const today   = todayISO();
    const in7days = inDaysISO(7);
    const in30days = inDaysISO(30);

    // ── 1. Overdue payments ────────────────────────────────────────────────
    const overdue = trackedPayments.filter((p) => p.status === 'pending' && p.dueDate < today);
    if (overdue.length) {
      const total = overdue.reduce((a, p) => a + p.amount, 0);
      insights.push({
        id: 'overdue_payments',
        emoji: '⚠️',
        title: `${overdue.length} overdue payment${overdue.length > 1 ? 's' : ''}`,
        body: `${formatINR(total)} past due — ${overdue.map((p) => p.title).slice(0, 2).join(', ')}${overdue.length > 2 ? ` +${overdue.length - 2} more` : ''}`,
        severity: 'danger',
        question: 'Do I have any overdue payments?',
        linkTo: '/payments',
      });
    }

    // ── 2. Payments due this week ─────────────────────────────────────────
    const dueWeek = trackedPayments.filter((p) => p.status === 'pending' && p.dueDate >= today && p.dueDate <= in7days);
    if (dueWeek.length && !overdue.length) {
      const total = dueWeek.reduce((a, p) => a + p.amount, 0);
      insights.push({
        id: 'payments_due_week',
        emoji: '🔔',
        title: `${dueWeek.length} payment${dueWeek.length > 1 ? 's' : ''} due this week`,
        body: `${formatINR(total)} total — ${dueWeek.map((p) => p.title).slice(0, 2).join(', ')}`,
        severity: 'warning',
        question: 'What payments are due in the next 7 days?',
        linkTo: '/payments',
      });
    }

    // ── 3. Insurance renewing within 30 days ──────────────────────────────
    const renewingSoon = insurancePolicies.filter(
      (p) => p.renewalDate && p.renewalDate >= today && p.renewalDate <= in30days,
    );
    if (renewingSoon.length) {
      insights.push({
        id: 'insurance_renewal',
        emoji: '🛡️',
        title: `Insurance renewal upcoming`,
        body: `${renewingSoon.map((p) => p.policyName).join(', ')} — renew${renewingSoon.length > 1 ? 's' : 's'} within 30 days`,
        severity: 'warning',
        question: 'Which insurance policies are renewing soon?',
        linkTo: '/insurance',
      });
    }

    // ── 4. Portfolio loss alert ───────────────────────────────────────────
    const stocks = investments.filter((i) => i.type === 'stock');
    if (stocks.length) {
      const losingStocks = stocks.filter((s) => {
        const iv = investedValue(s);
        const cv = currentValue(s);
        return cv < iv;
      });
      if (losingStocks.length) {
        const totalLoss = losingStocks.reduce((a, s) => a + (investedValue(s) - currentValue(s)), 0);
        insights.push({
          id: 'portfolio_loss',
          emoji: '📉',
          title: `${losingStocks.length} stock${losingStocks.length > 1 ? 's' : ''} in loss`,
          body: `Unrealized loss: ${formatINR(totalLoss)} across ${losingStocks.length} holding${losingStocks.length > 1 ? 's' : ''}`,
          severity: 'warning',
          question: 'Which of my investments is currently at the biggest loss?',
          linkTo: '/investments',
        });
      }
    }

    // ── 5. High debt-to-asset ratio ────────────────────────────────────────
    if (investments.length || liabilities.length) {
      const { totalAssets, totalLiabilities } = calculateNetWorth(investments, liabilities);
      const ratio = totalAssets > 0 ? (totalLiabilities / totalAssets) * 100 : 0;
      if (ratio > 50) {
        insights.push({
          id: 'high_debt_ratio',
          emoji: '💳',
          title: 'High debt-to-asset ratio',
          body: `${formatNumber(ratio, 1)}% of your assets are financed by debt`,
          severity: ratio > 70 ? 'danger' : 'warning',
          question: 'What is my debt-to-asset ratio?',
          linkTo: '/liabilities',
        });
      }
    }

    // ── 6. Goal near completion ───────────────────────────────────────────
    const activeGoals = goals.filter((g) => !g.status || g.status === 'active');
    for (const g of activeGoals) {
      const contributed = goalContributions.filter((c) => c.goalId === g.id).reduce((a, c) => a + c.amount, 0);
      const saved       = g.currentAmount + contributed;
      const progress    = g.targetAmount > 0 ? (saved / g.targetAmount) * 100 : 0;
      if (progress >= 80 && progress < 100) {
        insights.push({
          id: `goal_near_${g.id}`,
          emoji: '🎯',
          title: `${g.name} is ${formatNumber(progress, 0)}% complete!`,
          body: `${formatINR(Math.max(0, g.targetAmount - saved))} remaining to reach your target of ${formatINR(g.targetAmount)}`,
          severity: 'good',
          question: 'Which of my financial goals is closest to completion?',
          linkTo: '/goals',
        });
        break; // show at most one goal insight
      }
    }

    // ── 7. Lending overdue ────────────────────────────────────────────────
    const overdueLoans = lendingBorrowers.filter(
      (b) => b.status === 'active' && b.nextDueDate && b.nextDueDate < today,
    );
    if (overdueLoans.length) {
      const stats = overdueLoans.map((b) => {
        const txns    = lendingTransactions.filter((t) => t.borrowerId === b.id);
        const given   = txns.filter((t) => t.type === 'principal_given').reduce((a, t) => a + t.amount, 0);
        const returned= txns.filter((t) => t.type === 'principal_returned').reduce((a, t) => a + t.amount, 0);
        return given - returned;
      });
      const totalOut = stats.reduce((a, v) => a + v, 0);
      insights.push({
        id: 'lending_overdue',
        emoji: '🤝',
        title: `${overdueLoans.length} overdue repayment${overdueLoans.length > 1 ? 's' : ''}`,
        body: `${formatINR(totalOut)} outstanding — ${overdueLoans.map((b) => b.name).slice(0, 2).join(', ')}`,
        severity: 'warning',
        question: 'Are any of my lending repayments overdue?',
        linkTo: '/lending' as string,
      });
    }

    // ── 8. Low savings rate ────────────────────────────────────────────────
    if (cashflows.length >= 2) {
      const income  = cashflows.filter((e) => e.type === 'income');
      const expense = cashflows.filter((e) => e.type === 'expense');
      if (income.length && expense.length) {
        const totalInc = income.reduce((a, e) => a + e.amount, 0);
        const months   = new Set(income.map((e) => e.date.slice(0, 7))).size || 1;
        const avgInc   = totalInc / months;
        const totalExp = expense.reduce((a, e) => a + e.amount, 0);
        const avgExp   = totalExp / (new Set(expense.map((e) => e.date.slice(0, 7))).size || 1);
        const rate     = avgInc > 0 ? ((avgInc - avgExp) / avgInc) * 100 : 0;
        if (rate < 10 && avgInc > 0) {
          insights.push({
            id: 'low_savings_rate',
            emoji: '💸',
            title: `Low savings rate (${formatNumber(rate, 1)}%)`,
            body: `You are saving less than 10% of your income on average`,
            severity: rate < 0 ? 'danger' : 'warning',
            question: 'How much money am I saving each month?',
            linkTo: '/cashflow',
          });
        }
      }
    }

    // ── 9. Spending spike — this month vs 3-month average ─────────────────
    if (cashflows.length >= 4) {
      const now        = new Date();
      const thisMonth  = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
      const thisMonthExp = cashflows
        .filter((e) => e.type === 'expense' && e.date.startsWith(thisMonth))
        .reduce((a, e) => a + e.amount, 0);

      // 3-month average excluding current month
      const prevMonths = new Set(
        cashflows
          .filter((e) => e.type === 'expense' && !e.date.startsWith(thisMonth))
          .map((e) => e.date.slice(0, 7)),
      );
      const recentMonths = [...prevMonths].sort().slice(-3);
      if (recentMonths.length >= 2 && thisMonthExp > 0) {
        const prevTotal = cashflows
          .filter((e) => e.type === 'expense' && recentMonths.includes(e.date.slice(0, 7)))
          .reduce((a, e) => a + e.amount, 0);
        const avg3Month = prevTotal / recentMonths.length;
        const spikePct  = avg3Month > 0 ? ((thisMonthExp - avg3Month) / avg3Month) * 100 : 0;
        if (spikePct >= 20) {
          insights.push({
            id: 'spending_spike',
            emoji: '🔴',
            title: `Spending is ${formatNumber(spikePct, 0)}% higher than usual`,
            body: `This month: ${formatINR(thisMonthExp)} vs ${formatINR(avg3Month)} avg (last ${recentMonths.length} months)`,
            severity: spikePct >= 40 ? 'danger' : 'warning',
            question: 'Why is my spending higher this month?',
            linkTo: '/cashflow',
          });
        }
      }
    }

    // ── 10. Credit utilisation (credit card liabilities) ──────────────────
    const creditCards = liabilities.filter(
      (l) => l.type === 'credit_card' && (!l.status || l.status === 'active'),
    );
    if (creditCards.length > 0) {
      // Treat principal as credit limit, outstanding as used amount
      const totalLimit = creditCards.reduce((a, l) => a + (l.principal ?? 0), 0);
      const totalUsed  = creditCards.reduce((a, l) => a + (l.outstanding ?? 0), 0);
      const utilPct    = totalLimit > 0 ? (totalUsed / totalLimit) * 100 : 0;
      if (utilPct >= 40) {
        insights.push({
          id: 'credit_utilisation',
          emoji: '🟠',
          title: `Credit utilisation at ${formatNumber(utilPct, 0)}%`,
          body: `${formatINR(totalUsed)} used of ${formatINR(totalLimit)} limit — keep below 30% for good credit health`,
          severity: utilPct >= 70 ? 'danger' : 'warning',
          question: 'What is my credit card utilisation?',
          linkTo: '/liabilities',
        });
      }
    }

    // ── 11. Savings milestone win ──────────────────────────────────────────
    if (cashflows.length >= 2) {
      const incEntries = cashflows.filter((e) => e.type === 'income');
      const expEntries = cashflows.filter((e) => e.type === 'expense');
      if (incEntries.length && expEntries.length) {
        const incMonths = new Set(incEntries.map((e) => e.date.slice(0, 7))).size || 1;
        const avgInc    = incEntries.reduce((a, e) => a + e.amount, 0) / incMonths;
        const expMonths = new Set(expEntries.map((e) => e.date.slice(0, 7))).size || 1;
        const avgExp    = expEntries.reduce((a, e) => a + e.amount, 0) / expMonths;
        const rate      = avgInc > 0 ? ((avgInc - avgExp) / avgInc) * 100 : 0;

        // Show a "win" badge only if rate is notably good (>= 30%) and no danger alerts firing
        const hasDangerAlready = insights.some((i) => i.severity === 'danger');
        if (rate >= 30 && !hasDangerAlready) {
          insights.push({
            id: 'savings_win',
            emoji: '🟢',
            title: `Great savings rate — ${formatNumber(rate, 1)}%!`,
            body: `You are saving ${formatINR(avgInc - avgExp)}/mo on average. Keep it up!`,
            severity: 'good',
            question: 'How much money am I saving each month?',
            linkTo: '/cashflow',
          });
        }
      }
    }

    // ── 12. Emergency fund dropped below 3 months ─────────────────────────
    const emergencyTarget  = essentials?.emergencyFundTarget  ?? 0;
    const emergencyCurrent = essentials?.emergencyFundCurrent ?? 0;
    const expForRunway     = (() => {
      const exp = cashflows.filter((e) => e.type === 'expense');
      if (!exp.length) return 0;
      const months = new Set(exp.map((e) => e.date.slice(0, 7))).size || 1;
      return exp.reduce((a, e) => a + e.amount, 0) / months;
    })();
    const runwayMonths = expForRunway > 0 ? emergencyCurrent / expForRunway : 0;

    if (emergencyTarget > 0 || emergencyCurrent > 0) {
      if (runwayMonths > 0 && runwayMonths < 3) {
        insights.push({
          id: 'emergency_fund_low',
          emoji: '🔴',
          title: `Emergency fund below 3 months`,
          body: `You have ${formatNumber(runwayMonths, 1)} months of runway — target is 6 months (${formatINR(expForRunway * 6)})`,
          severity: runwayMonths < 1 ? 'danger' : 'warning',
          question: 'How is my emergency fund?',
          linkTo: '/insights',
        });
      } else if (emergencyTarget > 0 && emergencyCurrent < emergencyTarget * 0.5) {
        const pct = (emergencyCurrent / emergencyTarget) * 100;
        insights.push({
          id: 'emergency_fund_low',
          emoji: '🔴',
          title: `Emergency fund at ${formatNumber(pct, 0)}% of target`,
          body: `${formatINR(emergencyCurrent)} saved of ${formatINR(emergencyTarget)} goal`,
          severity: 'warning',
          question: 'How is my emergency fund?',
          linkTo: '/insights',
        });
      }
    }

    // ── 13. Goal ahead of schedule ────────────────────────────────────────
    for (const g of activeGoals) {
      if (!g.dueDate) continue;
      const contributed = goalContributions.filter((c) => c.goalId === g.id).reduce((a, c) => a + c.amount, 0);
      const saved       = g.currentAmount + contributed;
      const now         = new Date();
      const due         = new Date(g.dueDate);
      const totalMonths = Math.max(1,
        (due.getFullYear() - new Date(g.createdAt).getFullYear()) * 12 +
        (due.getMonth() - new Date(g.createdAt).getMonth()),
      );
      const elapsedMonths = Math.max(0,
        (now.getFullYear() - new Date(g.createdAt).getFullYear()) * 12 +
        (now.getMonth() - new Date(g.createdAt).getMonth()),
      );
      const expectedPct = totalMonths > 0 ? (elapsedMonths / totalMonths) * 100 : 0;
      const actualPct   = g.targetAmount > 0 ? (saved / g.targetAmount) * 100 : 0;
      const lead        = actualPct - expectedPct;

      if (lead >= 15 && actualPct < 100) {
        const leadAmount = Math.round((lead / 100) * g.targetAmount);
        insights.push({
          id: `goal_lead_${g.id}`,
          emoji: '🟢',
          title: `Ahead on "${g.name}" by ${formatINR(leadAmount)}`,
          body: `${formatNumber(actualPct, 0)}% saved vs ${formatNumber(expectedPct, 0)}% expected at this point — you're ${formatNumber(lead, 0)}% ahead`,
          severity: 'good',
          question: 'Which of my goals is ahead of schedule?',
          linkTo: '/goals',
        });
        break; // one goal-lead insight at a time
      }
    }

    // Return at most 5 (increased from 4 to accommodate new alert types)
    return insights.slice(0, 5);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    investments, liabilities, cashflows, trackedPayments,
    insurancePolicies, goals, goalContributions,
    lendingBorrowers, lendingTransactions, essentials,
  ]);
}
